# Container image variables
container:
  name: nginx # Container name
  image: nginx:latest # Container image that you deploy to the cluster

containerSidecar:
  name: integrity # Container name
  image: integrity:latest # Container image that you deploy to the cluster

# Name and identifier variables
metadata:
  deploymentName: nginx-integrity # Set the unique name for deployment schema
  appName: nginx-app # Application name label

# Service account name
serviceAccount: integrity

# Number of replicas
replicaCount: 1

# Configuration file variables
configMap:
  name: integrity-sum-config
  processName: nginx # Container process name
  mountPath: etc/nginx # Tracdb5ed folder path
  splunkUrl: "" # url to send events https://splunk:8088/services/collector/event
  splunkToken: ""
  splunkInsecureSkipVerify: true
  syslog:
    enabled: false
    host: "rsyslog"
    port: "514"
    proto: "tcp"

releaseNameDB: ""

# The DB connection data. Should be overridden by actual values
db:
  port: 5432
  database: ""
  username: ""
