apiVersion: integrity.snapshot/v1
kind: Snapshot
metadata:
  labels:
    app.kubernetes.io/name: snapshot
    app.kubernetes.io/instance: snapshot-sample
    app.kubernetes.io/part-of: crd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: crd
  name: snapshot-sample
  finalizers:
  - controller.snapshot/finalizer
spec:
  image: integrity:latest
  hashes: Zm9vYmFyYQ==
