apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-{{ .Values.metadata.deploymentName }}
  labels:
    app: {{ .Values.metadata.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.appName }}
        main-process-name: "{{ .Values.configMap.processName }}"
      annotations:
        integrity-monitor.scnsoft.com/inject: "true"
        integrity-monitor.scnsoft.com/process: nginx
        integrity-monitor.scnsoft.com/monitoring-path: etc/nginx
    spec:
      serviceAccountName: {{.Release.Name}}-{{ .Values.serviceAccount }}
      shareProcessNamespace: true
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}
          stdin: true
          tty: true

        - name: {{ .Values.containerSidecar.name }}
          image: {{ .Values.containerSidecar.image }}
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: {{ .Values.releaseNameDB }}-{{ .Values.secretNameDB}} # Name of the secret environmental variable file to load from database
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DEPLOYMENT_TYPE
              value: deployment
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          stdin: true
          tty: true
