{{- $secretMinio := (lookup "v1" "Secret" .Values.minio.namespace .Values.minio.secret.name).data | default dict }}
{{- $minioUser := (get $secretMinio "root-user") | default dict }}
{{- $minioPassword := (get $secretMinio "root-password") | default dict }}
---
{{- if $secretMinio }}
apiVersion: v1
kind: Secret
data:
  root-user: {{ $minioUser }}
  root-password: {{ $minioPassword }}
metadata:
  labels:
  name: minio
  namespace: {{ .Release.Namespace }}
{{- end }}
