apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-{{ .Values.serviceAccount }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Release.Name}}-{{ .Values.serviceAccount }}
rules:
  - apiGroups: ["apps"]
    verbs: ["patch", "get", "list"]
    resources:
      - deployments
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Release.Name}}-{{ .Values.serviceAccount }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.Release.Name}}-{{ .Values.serviceAccount }}
subjects:
  - kind: ServiceAccount
    name: {{.Release.Name}}-{{ .Values.serviceAccount }}
