# permissions for end users to view snapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: snapshot-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crd
    app.kubernetes.io/part-of: crd
    app.kubernetes.io/managed-by: kustomize
  name: snapshot-viewer-role
rules:
- apiGroups:
  - integrity.integrity
  resources:
  - snapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integrity.integrity
  resources:
  - snapshots/status
  verbs:
  - get
