apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-{{ .Values.secretName}}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:  # We don't need to worry about converting to base64
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password }}"
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}

  DB_HOST: {{.Release.Name}}-postgresql
  DB_DRIVER: postgres
  DB_USER: {{ .Values.postgresql.auth.username }}
  DB_PASSWORD: "{{ .Values.postgresql.auth.password }}"
  DB_NAME: {{ .Values.postgresql.auth.database }}
  DB_PORT: "{{ .Values.postgresql.primary.service.port}}"
