# Dependency to database "postgresql"
# Set the unique name for secret for database
secretName: ""

postgresql:
  auth:
    # Authentication data to connect to the database, need to set
    postgresPassword: ""
    username: ""
    password: ""
    database: ""
    postgresqlDataDir: /bitnami/postgresql/data

  primary:
    # Enable security context
    podSecurityContext:
      enabled: false
      fsGroup: ""
    # Enable container security context
    containerSecurityContext:
      enabled: false
      runAsUser: "auto"
    service:
      ## PosgresSQL service type
      type: ClusterIP
      # clusterIP: None
      port: 5432

    persistence:
      # Enable PostgreSQL Primary data persistence using PVC
      enabled: true
      existingClaim: ""
      # mountPath: /bitnami/postgresql - default mountPath
      accessModes:
        - ReadWriteMany
      size: 5Gi

    #Enable security context
    readReplicas:
      podSecurityContext:
        enabled: false
        fsGroup: ""
      containerSecurityContext:
        enabled: false
        runAsUser: "auto"

    # Enable init container that changes the owner and group of the persistent volume
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: "auto"
